FROM centos:7.7.1908
MAINTAINER support@versity.com

ADD . / ./

RUN yum --disablerepo=updates -y install rpm-build redhat-rpm-config make gcc git vi tar unzip rpmlint kernel-devel && yum clean all

RUN make dist
RUN rpmbuild --define "kversion 3.10.0-1062.el7.x86_64" -tb *.tar